[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "5.0.0"

[[constraint]]
  name = "github.com/dchest/blake2b"

[[constraint]]
  name = "github.com/go-openapi/runtime"

[[constraint]]
  name = "github.com/manifoldco/go-base32"
  version = "1.0.0"
